### ISSUE TITLE
Cannot find module 'popper.js' or its corresponding type declarations

### ISSUE THREAD

**Issue by seseso** [creativetimofficial/notus-angular#4]
### Version
1.0.0
### Reproduction link
http://i-dont-have-a reproducer.com
### Operating System
Ubuntu
### Device
-
### Browser & Version
-
### Steps to reproduce
1. git clone
2. npm run install:clean
### What is expected?
The project should compile without errors
### What is actually happening?
There are compilation errors

---

**Comment by gkimpson** [comment]
I am having the exact same issue running the following 
```
Mac OS Big Sur
Node - 14.15.1
NPM 6.14.8

Have run the npm install:clean command and just loaded up this in browser (get a white screen) whilst I get the same error in several places

.e.g
    src/app/components/dropdowns/user-dropdown/user-dropdown.component.ts:2:20 - error TS2307: Cannot find module 'popper.js' or its corresponding type declarations.


```

**Comment by vicelao** [comment]
![image](https://user-images.githubusercontent.com/33270493/100543447-fe398900-322e-11eb-9cbb-b28835e8321a.png)

I have the same problem.

**Comment by vicelao** [comment]
Guys, please run this line in terminal:

`npm install @types/popper.js`

This will resolve the problem.

**Comment by AlonSerrano** [comment]
Please use

`import { createPopper } from '@popperjs/core';`

and change 

`createPoppper() {
    createPopper(this.btnDropdownRef.nativeElement, this.popper, {
      placement: "bottom-end",
    });
    this.btnDropdownRef.nativeElement.parentNode.insertBefore(
      this.popper,
      this.btnDropdownRef.nativeElement.nextSibling
    );
  }`


Popper v1 is [deprecated](https://www.npmjs.com/package/popper.js/v/1.14.3)

**Comment by EINazare** [comment]
Hello guys,

Sorry for this late reply, Github did not notify me about this issue.
Glad that a solution was found. We'll make an update in about 2 months to the project and solve this as well.

Best,
Manu

**Comment by drjorgepolanco** [comment]
If somebody is having this issue on Rails, I had the issue trying to install Bootstrap. 
This is what worked for me:

- yarn add bootstrap@5.0.0
- yarn add jquery
- yarn add @popperjs/core

**Comment by EINazare** [comment]
Hello there, @drjorgepolanco ,

Thank you for sharing this with us.
It is a bit weird that you are adding `Bootstrap` on a `Tailwind CSS` project.
I think you should delete `node_modules` and `package-lock.json` and `yarn-lock.json` if you have any, and try installing the product with `npm` instead of `yarn`.

Best,
Manu

**Comment by shubham-selldo** [comment]
> If somebody is having this issue on Rails, I had the issue trying to install Bootstrap. This is what worked for me:
> 
> * yarn add bootstrap@5.0.0
> * yarn add jquery
> * yarn add @popperjs/core

Thanks @drjorgepolanco this worked for me with rails 7
